[build]
  command = "pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/pokedex"
  to = "/pokedex/index.html"
  status = 200

[[redirects]]
  from = "/equipo"
  to = "/equipo/index.html"
  status = 200
